#
# create: JoseQuintas/addons/mingw_0703

name: mingw 7.3

on:
#  push:
  schedule:
   - cron: "0 5 1 * *"
  workflow_dispatch:
    inputs:
      name:
        description: 'mingw 7.3 32bits'
        default: 'mingw_0703'
        required: true

jobs:

  Build:
    runs-on: windows-latest
    steps:

    - name: mingw 7.3
      uses: dawidd6/action-download-artifact@v2
      with:
         workflow: mingw_0703.yml
         workflow_conclusion: success
         name: mingw_0703
         path: c:\temp
         repo: JoseQuintas/addons

    - name: Save
      uses: actions/upload-artifact@v3
      with:
         name: mingw_0703
         path: c:\temp\mingw_0703.7z
